export const CART_AGREGARITEM = 'CART/AGREGAR_ITEM';
export const CART_BORRARITEM = 'CART/BORRAR_ITEM';
export const CART_AUMENTARCANTIDAD = 'CART/AUMENTARCANTIDAD';
export const CART_REDUCIRCANTIDAD = 'CART/REDUCIRCANTIDAD';